export enum UserRole {
    ADMIN='ADMIN',
    DEPO='DEPO',
    RETAILER='RETAILER',
    PURCHASE_MANAGER='PURCHASE_MANAGER',
    DELIVERY_BOY='DELIVERY_BOY',
    HAWKER='HAWKER',
    CUSTOMER='CUSTOMER',
    MANUFACTURING_PLANT='MANUFACTURING_PLANT',
    SUPPLIER='SUPPLIER'
}